= Open Awareness Training (OpenAT) Containeried Build Environment
To help package the build environment for Open Awareness Training (OpenAT), we are leveraging containerization.

== Build dependancies
On the machine which will be running this container you need to have the following installed.

* A container build environment (the build script uses one of these in the priority listed below)
** Buildah
** Podman
** Docker
* rsync
* bash
* Python3
* GNU Make

== Building OpenAT Container
To build and push the container to a registry you have push access to:

[source,bash]
----
export FULLTAG=ghcr.io/openawarenesstraining/openawarenesstraining
bin/buildenv
----

This builds the container locally and pushes a copy to the tag in `${FULLTAG}`.

== Running the OpenAT Container
The makefile targets which build the courseware need to run *INSIDE* the container's context.

Here's how you start the environment and render the content:

[source,bash]
----
export FULLTAG=ghcr.io/openawarenesstraining/openawarenesstraining
bin/runenv
[root@73d277417335 source]# make
<lots of output and course is rendered in output/ folder>
----

[.NOTE]
====
If you are running `podman` or `docker` with SELinux enabled, you may need to exit the
ZOST container and re-run `bin/runenv` to reset SELinux permissions on files you add
to the working directory after the last time you ran `bin/runenv`.

== Other Make targets
There are some other `make` targets which help with course development

=== Cleanup targets

==== Targets which should be ran inside the container:
The following targets should be only run inside the container.

`make clean` -- removes all rendered html content

`make nuke` -- removes all rendered html content and the shared files (node modules slideshow css etc)

==== Targets which should be ran *OUTSIDE* the container
The following target should only be run from outside the container (aka before running `bin/runenv`)

`make server` -- starts a web server listening on http://localhost:8000

